services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${secrets.DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${secrets.DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${secrets.DATABASE_USER}
      MYSQL_PASSWORD: ${secrets.DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
